REM
REM Batch file generated by MOHID Studio a :  2019-04-26 11:30:16
REM
COPY "D:\Aplica\temp\Tanque_teste\data\Nomfich_1.dat" "D:\Aplica\temp\Tanque_teste\exe\Nomfich.dat"
COPY "D:\Aplica\temp\Tanque_teste\Level2\data\Nomfich_1.dat" "D:\Aplica\temp\Tanque_teste\Level2\exe\Nomfich.dat"
D:
CD "D:\Aplica\temp\Tanque_teste\exe"
"D:\Aplica\temp\Tanque_teste\exe\MOHIDWater.exe"
PAUSE
